version: "3.9"
networks:
  myAppNetwork:
    driver: bridge

services:
  db:
    container_name: pg-container
    image: postgres:17
    environment:
      POSTGRES_USER: krot
      POSTGRES_PASSWORD: p%rSDj4Imds0763300sfgs7djc**dmUntdOidd3dZ_#WTi4B9Zo
      POSTGRES_DB: cosmeria
    volumes:
      - /volumes/cosmeria/postgres/data:/var/lib/cosmeria/data
    ports:
      - "5432:5432"
    networks:
      - myAppNetwork
    restart: unless-stopped
  app:
    container_name: cosmeria_container
    image: komarandrii/cosmeria-asp-api
    ports:
      - "5817:8080"  
    networks:
      - myAppNetwork
    environment:
        ConnectionStrings__DefaultConnection: "Host=db;Database=cosmeria;Username=krot;Password=p%rSDj4Imds0763300sfgs7djc**dmUntdOidd3dZ_#WTi4B9Zo"
        Cors__AllowedOrigins: "https://cosmeria.rivne.click"
    volumes:
      - /volumes/cosmeria-asp/backup:/app/backup 
      - /volumes/cosmeria-asp/images:/app/uploading
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 5

  client:
    container_name: cosmeria_client_container
    image: komarandrii/cosmeria-client
    restart: on-failure
    ports:
      - "5092:80"  
    networks:
      - myAppNetwork
